public class VFPageEX {
    public  string name {set; get;}
    public string gender {set; get;}
    public integer age {set; get;}
    public string city{set; get;}
    public void callMe(){
        
        name='Sai Kiran';
        gender  ='Male';
        age=32;
        city ='Toronto';
       
    }
    public void invoke(){
        
        name='Sai';
        gender  ='Male';
        age=35;
        city ='Hyderabad';
       
    }
    
    
}